//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargoAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CARGOEntities1 : DbContext
    {
        public CARGOEntities1()
            : base("name=CARGOEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAR_CLIENT> CAR_CLIENT { get; set; }
        public virtual DbSet<CAR_DEF_BOOK_TYPE> CAR_DEF_BOOK_TYPE { get; set; }
        public virtual DbSet<CAR_DEF_BRANCH> CAR_DEF_BRANCH { get; set; }
        public virtual DbSet<CAR_DEF_BUS_NATURE> CAR_DEF_BUS_NATURE { get; set; }
        public virtual DbSet<CAR_DEF_SUP_TYPE> CAR_DEF_SUP_TYPE { get; set; }
        public virtual DbSet<CAR_SUPPLIER> CAR_SUPPLIER { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<CAR_CLIENT_DIR> CAR_CLIENT_DIR { get; set; }
        public virtual DbSet<CAR_DEF_CLIENT_TYPE> CAR_DEF_CLIENT_TYPE { get; set; }
        public virtual DbSet<CAR_INQ> CAR_INQ { get; set; }
        public virtual DbSet<CAR_DEF_ACC_MGR> CAR_DEF_ACC_MGR { get; set; }
        public virtual DbSet<CAR_DEF_BUS_TYPE> CAR_DEF_BUS_TYPE { get; set; }
        public virtual DbSet<CAR_DEF_CLIENT_STATUS> CAR_DEF_CLIENT_STATUS { get; set; }
    }
}
